root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/worker"
cmd = "go build -o ./tmp/worker ./cmd/server"
args_bin = ["worker", "--temporal-address", "localhost:7233", "--temporal-namespace", "default", "--task-queue", "{{cookiecutter.project_slug}}"]
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "bin", "logs", "data", "k8s", "migrations"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_regex = ["_test\\.go"]
kill_delay = "2s"

[log]
time = false

[misc]
clean_on_exit = true
